version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/stuy-spec-api
    steps:
      - checkout

      - run: |
          sudo apt-get install python-dev python-pip
          sudo pip install awsebcli --upgrade --user
          cd
          git clone https://github.com/stuyspec/stuyspec.com.git
          cd stuyspec.com
          git checkout master
          sudo apt-get install npm
          npm install
          npm run build
          mv build client-app
          cd
          cd stuy-spec-api
          git checkout master
          cp -af ~/client-app/client-app public/
          cd
          zip -r ~/stuy-spec-api/archive/api.zip ~/stuy-spec-api
      - deploy:
          name: Deploy to AWS S3
          command: |
            #if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              #aws s3 sync ~/client-app/dist/prod s3://staging.stuyspec.com
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              eb deploy --staged
            else
              echo "We do not deploy on the ${CIRCLE_BRANCH} branch."
            fi
