version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/client-app
    steps:
      - checkout

      - run: |
          sudo apt-get install python-dev python-pip
          pip install awsebcli --upgrade --user
          cd
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: |
          npm install
          CI=false npm run build
          mv build client-app
          cd
          git clone https://github.com/stuyspec/stuyspec-api.git
          cd stuyspec-api
          git checkout master
          cp -af ~/client-app/client-app/. public
          cd
          zip -r ~/api.zip ~/stuyspec-api
          mkdir ~/stuyspec-api/archive
          mv -f ~/api.zip ~/stuyspec-api/archive/
      - deploy:
          name: Deploy to AWS S3
          command: |
            #if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              #aws s3 sync ~/client-app/dist/prod s3://staging.stuyspec.com
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd ~/stuyspec-api
              printf "1\n1\n\n" | ~/.local/bin/eb init
              ~/.local/bin/eb deploy --staged
            else
              echo "We do not deploy on the ${CIRCLE_BRANCH} branch."
            fi
